# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QdKF4kv4OSyYfA4vnix-dGvEwNGXZr8
"""

import pandas as pd
import numpy as np
from IPython.display import FileLink, display

# =====================================================================
# TASK 2: EXPLORATORY DATA ANALYSIS (EDA)
# Domain: Data Analytics
# =====================================================================

print("==================================================================")
print("📌 STEP 1: INITIAL HYPOTHESES & MEANINGFUL QUESTIONS")
print("==================================================================")
print("Before looking at the metrics, we pose 4 foundational questions:")
print("1. What is the breakdown of data types across our tracking metrics?")
print("2. Are popularity scores skewed toward a specific rating zone?")
print("3. Does a track's energy levels scale linearly with its loudness?")
print("4. What volume of missing data exists, and where is it located?\n")

print("==================================================================")
print("📌 STEP 2: LOADING DATA & STRUCTURE EXPLORATION")
print("==================================================================")
# Direct web link to the dataset to bypass local file errors
web_url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv"
df = pd.read_csv(web_url)

# Checking structural layout (Rows vs Columns)
rows, cols = df.shape
print(f"• Total Data Observations (Rows): {rows}")
print(f"• Total Feature Attributes (Columns): {cols}\n")

# Display breakdown of variables and data types
print("Detailed Summary of Variables and Schema Types:")
print(df.info())
print("\n")

print("==================================================================")
print("📌 STEP 3: STATISTICAL PATTERNS & TREND IDENTIFICATION")
print("==================================================================")
# Descriptive statistics for primary numerical metrics
metrics_of_interest = ['track_popularity', 'danceability', 'energy', 'loudness', 'tempo']
print("Descriptive Statistical Summary of Main Audio Features:")
print(df[metrics_of_interest].describe())
print("\n")

# Uncovering patterns by grouping data by Music Genre
print("Average Feature Value Trends Across Different Music Genres:")
genre_trends = df.groupby('playlist_genre')[['track_popularity', 'energy', 'tempo']].mean()
print(genre_trends)
print("\n")

print("==================================================================")
print("📌 STEP 4: ANOMALY & DATA ISSUE DETECTION")
print("==================================================================")
# Identifying explicit missing values (Nulls)
missing_values = df.isnull().sum()
print("Missing Value Counts Across Columns:")
print(missing_values[missing_values > 0] if missing_values.sum() > 0 else "No missing values found!")
print("\n")

# Detecting structural anomalies (e.g., checking for duplicated track IDs)
duplicate_tracks = df.duplicated(subset=['track_id']).sum()
print(f"• Anomaly Alert: Found {duplicate_tracks} duplicate track entries in the dataset.")
print("==================================================================")

print("\n🎉 TASK 2 COMPLETE!")
print("Go to File > Download > Download .ipynb to save this notebook file.")